### ISSUE TITLE
extra_configurations for 'hadoop.security.authentication' not works

### ISSUE THREAD

**Issue by kysersozelee** [choplin/embulk-output-parquet#10]
I try to import data and export to hdfs by using embulk-output-parquet library.
But when I run embulk by below settings,  "Error: java.lang.RuntimeException: org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS] " exception occurred.

```
in:
  type: mysql
  host: 192.168.65.2
  port: 3306
  user: user
  password: "pwd"
  database: testdb
  table: testtable
  options: { useLegacyDatetimeCode: true }
out:
  type: parquet
  path_prefix: hdfs://{url}/tmp/embulk
  extra_configurations:
    hadoop.security.authentication: 'KERBEROS'
  config_files:
    - {HADOOP_CONFIG_HOME}/hdfs-site.xml
    - {HADOOP_CONFIG_HOME}/core-site.xml
```

kerberos setting is ok all, and I inserted code for checking 'hadoop.security.authentication' is really set by 'SIMPLE'. But 'KEBEROS' value was overwrited correctly. I guess even though set by any string, it is overwrited by 'SIMPLE' somewhere. 

os : hadoop
embulk : v0.97
haddop : hadoop-2.6.0-cdh5.14.2

related issue I found : https://github.com/civitaspo/embulk-output-hdfs/issues/17
